/** @format */

import type { Metadata } from "next";
import { ThemeProvider } from "@/modules/common/components/theme-provider";
import "@fontsource-variable/playfair-display";
import "@fontsource-variable/dancing-script";
import "@fontsource-variable/raleway";
import "./globals.css";
import ClientProvider from "@/layout/components/client-provider";
import { Toaster } from "@/modules/common/ui/sonner";

export const metadata: Metadata = {
  title: "ReelBlend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang='en' suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem
            disableTransitionOnChange>
            <div id='overlay' />
            <ClientProvider>{children}</ClientProvider>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
